name: demo-build
on: pull_request
jobs:
  build:
    name: Demo Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code with history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npx nx affected:build
